services:
  - type: web
    name: engineering-faculty-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: GOOGLE_CLIENT_ID
        value: 231790850035-0f63f0dpqkeng3mh9783bg8ksposp3hg.apps.googleusercontent.com
      - key: VITE_GOOGLE_CLIENT_ID
        value: 231790850035-0f63f0dpqkeng3mh9783bg8ksposp3hg.apps.googleusercontent.com
